// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fijkufrhdgngluwjjzbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpamt1ZnJoZGduZ2x1d2pqemJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDg2ODAsImV4cCI6MjA2NTk4NDY4MH0.M3sWo41121StJ6RqgT3mDO8uVgEbR5h4GUKBSWZvKIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);